version: '3.8'
services:
  api:
    build: .
    ports:
      - "8003:8080"
    depends_on:
      - redis
    environment:
      - Redis__ConnectionString=redis:6379,abortConnect=false

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: